name: Tryout Lib 100 Releases

on:
  release:
    types: [ prereleased ]

jobs:

  # Will publish the node package to Github packages
  publish-gpr:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Configure Node version and registry
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/

      - name: Install Dependencies
        run: npm install

      - name: Publish to GitHub Package Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}


  # Will publish the node package to NPM packages
  publish-npm:
    runs-on: ubuntu-latest
    needs: publish-gpr
    steps:

      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Rename Package name NPMJS release
        run: |
          sed 's/@bijujoseph\/tryout-lib100/tryout-lib100/g' package.json > tmp.json
          mv tmp.json package.json

      - name: Configure Node version and registry
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Publish to NPMJS
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  # Make an announcement to other repositories of interest
  repo-dispatch:
    runs-on: ubuntu-latest
    needs: publish-npm
    strategy:
      matrix:
        repo: ['bijujoseph/tryout-repo200']
    steps:

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.0
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          repository: bijujoseph/tryout-repo200
          event-type: lib-update-event
          client-payload: '{"ref": "${{ github.ref }}", "private_package": "@bijujoseph/tryout-lib100", "public_package":"tryout-lib100" ,"tag_name": "${{ github.event.release.tag_name }}", "html_url": "${{github.event.release.html_url}}"}'
