#
# This workflow will run post build quality checks
# and is invoked when the "Build - PR" workflow finishes.
#
name: Quality Checks

on:
  workflow_run:
    workflows: ["Tryout Lib 100"]
    types:
      - completed

jobs:
  perform-quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Debug
        uses: hmarr/debug-action@master


      - name: Print Folders
        run: ls -ltar

      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_commit.id }}

      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@891cccee4b25d3306cf5edafa174ddc1d969871f
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          commit: ${{ github.event.workflow_run.head_commit.id }}
          name: coverage
          path: coverage


      - name: Print Folders
        run: ls -ltar

      - name: Find PR Number
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: PR Number
        run: echo "Your PR is ${steps.findPr.outputs.number}"
          if: success() && steps.findPr.outputs.number
          env:
            PR: ${{ steps.findPr.outputs.number }}

      # set the only_changed_files to true on PR based builds, otherwise show full coverage
      - name: Produce Coverage report
        uses: 5monkeys/cobertura-action@b3d1f4899a5f2d30adc2a13ac2abcd9f72e1fe66 # pin@master
        if: ${{ github.event.workflow_run.event == 'pull_request' }}
        with:
          path: coverage/cobertura-coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          only_changed_files: ${{github.base_ref != null}}
          pull_request_number: ${{ steps.findPr.outputs.number }}
          show_line: true
          show_branch: true
          minimum_coverage: 90
