name: Tryout Lib 100 Release Notes
on:
  push:
    branches:
      - master

jobs:

  # Generate new release notes
  update_release_draft:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Detect and tag new version
        id: package-version
        uses: salsify/action-detect-and-tag-new-version@v1.0.3

      - name: Draft release notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          version: ${{ steps.package-version.outputs.current-version }}
          tag: ${{ steps.package-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
