name: Tryout Lib 100 Repo Dispat
on:
  registry_package:
    types: [published]
jobs:
  repo-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.0
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: bijujoseph/tryout-repo200
          event-type: lib-update-event
          client-payload: '{"github": ${{ toJson(github) }}}'
